id: ICE7FC2A8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:51:10+00:00'
last_modified: '2022-06-08T05:47:46.396222+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27021
  title: གྲུབ་ཆེན་ནམ་མཁའ་རྒྱལ་མཚན་གྱི་མཛད་རྣམ་ཐོར་བུ་དང་ན་སྟེང་དང་བཀྲ་ཤིས་གླིང་དགོན་གྱི་དཀར་ཆག་དོན་གསལ་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    847D:
      image_group_id: I1PD30384
      title: ''
      total_pages: 238
      order: 1
      base_file: 847D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
